# Prepend a "v" to the release version, for compatibility with Go's release conventions.
- op: add
  path: "/jobs/bump/env"
  value:
    BUMP_VERSION_RELEASE_PREFIX: v

# Cause proxy.golang.org (and pkg.go.dev) to refresh its cache for this package. https://proxy.golang.org/'s FAQ explains.
- op: add
  path: /jobs/bump/steps/-
  value:
    name: Announce the new release
    run: |
      mkdir foo
      cd foo
      go mod init example.com/m
      go get github.com/IronCoreLabs/tenant-security-client-go@${{ steps.release.outputs.release }}

# Pushing the tag will automatically publish to pkg.go.dev, so only bump version manually (to release)
- op: remove
  path: /on/push
