version: "2"
linters:
  enable:
  - asciicheck
  - bidichk
  - bodyclose
  - containedctx
  - contextcheck
  - dogsled
  - dupl
  - durationcheck
  # - err113
  - errchkjson
  - errname
  - errorlint
  - exhaustive
  # - forbidigo
  - forcetypeassert
  # - funlen
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godot
  - godox
  - gomoddirectives
  - goprintffuncname
  - gosec
  - grouper
  - importas
  - ireturn
  - lll
  - makezero
  - misspell
  # - mnd
  - nakedret
  - nilerr
  - nilnil
  - noctx
  - nolintlint
  - nonamedreturns
  - nosprintfhostport
  - prealloc
  - predeclared
  - promlinter
  - revive
  - rowserrcheck
  - sqlclosecheck
  - staticcheck
  - tagliatelle
  - thelper
  - tparallel
  - unconvert
  - unparam
  - varnamelen
  - wastedassign
  - whitespace
  - wrapcheck
  exclusions:
    generated: lax
    presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
    paths:
    - third_party$
    - builtin$
    - examples$
formatters:
  enable:
  - gci
  - gofmt
  - goimports
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
