// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: document_header.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataControlPlatformHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocumentId string `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	SegmentId  uint64 `protobuf:"varint,2,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
}

func (x *DataControlPlatformHeader) Reset() {
	*x = DataControlPlatformHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_document_header_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataControlPlatformHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataControlPlatformHeader) ProtoMessage() {}

func (x *DataControlPlatformHeader) ProtoReflect() protoreflect.Message {
	mi := &file_document_header_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataControlPlatformHeader.ProtoReflect.Descriptor instead.
func (*DataControlPlatformHeader) Descriptor() ([]byte, []int) {
	return file_document_header_proto_rawDescGZIP(), []int{0}
}

func (x *DataControlPlatformHeader) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DataControlPlatformHeader) GetSegmentId() uint64 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

type SaaSShieldHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
}

func (x *SaaSShieldHeader) Reset() {
	*x = SaaSShieldHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_document_header_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaaSShieldHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaaSShieldHeader) ProtoMessage() {}

func (x *SaaSShieldHeader) ProtoReflect() protoreflect.Message {
	mi := &file_document_header_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaaSShieldHeader.ProtoReflect.Descriptor instead.
func (*SaaSShieldHeader) Descriptor() ([]byte, []int) {
	return file_document_header_proto_rawDescGZIP(), []int{1}
}

func (x *SaaSShieldHeader) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type V3DocumentHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig []byte `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	// Types that are assignable to Header:
	//	*V3DocumentHeader_DataControl
	//	*V3DocumentHeader_SaasShield
	Header isV3DocumentHeader_Header `protobuf_oneof:"header"`
}

func (x *V3DocumentHeader) Reset() {
	*x = V3DocumentHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_document_header_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *V3DocumentHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V3DocumentHeader) ProtoMessage() {}

func (x *V3DocumentHeader) ProtoReflect() protoreflect.Message {
	mi := &file_document_header_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V3DocumentHeader.ProtoReflect.Descriptor instead.
func (*V3DocumentHeader) Descriptor() ([]byte, []int) {
	return file_document_header_proto_rawDescGZIP(), []int{2}
}

func (x *V3DocumentHeader) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (m *V3DocumentHeader) GetHeader() isV3DocumentHeader_Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (x *V3DocumentHeader) GetDataControl() *DataControlPlatformHeader {
	if x, ok := x.GetHeader().(*V3DocumentHeader_DataControl); ok {
		return x.DataControl
	}
	return nil
}

func (x *V3DocumentHeader) GetSaasShield() *SaaSShieldHeader {
	if x, ok := x.GetHeader().(*V3DocumentHeader_SaasShield); ok {
		return x.SaasShield
	}
	return nil
}

type isV3DocumentHeader_Header interface {
	isV3DocumentHeader_Header()
}

type V3DocumentHeader_DataControl struct {
	DataControl *DataControlPlatformHeader `protobuf:"bytes,2,opt,name=data_control,json=dataControl,proto3,oneof"`
}

type V3DocumentHeader_SaasShield struct {
	SaasShield *SaaSShieldHeader `protobuf:"bytes,3,opt,name=saas_shield,json=saasShield,proto3,oneof"`
}

func (*V3DocumentHeader_DataControl) isV3DocumentHeader_Header() {}

func (*V3DocumentHeader_SaasShield) isV3DocumentHeader_Header() {}

var File_document_header_proto protoreflect.FileDescriptor

var file_document_header_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x69,
	0x72, 0x6f, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x6c, 0x61, 0x62, 0x73, 0x2e, 0x63, 0x6d, 0x6b, 0x22,
	0x5b, 0x0a, 0x19, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x10,
	0x53, 0x61, 0x61, 0x53, 0x53, 0x68, 0x69, 0x65, 0x6c, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x22, 0xd3, 0x01,
	0x0a, 0x10, 0x56, 0x33, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x73, 0x69, 0x67, 0x12, 0x56, 0x0a, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x69, 0x72, 0x6f, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x6c, 0x61, 0x62, 0x73, 0x2e,
	0x63, 0x6d, 0x6b, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x50,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x0b, 0x64, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x4b, 0x0a, 0x0b,
	0x73, 0x61, 0x61, 0x73, 0x5f, 0x73, 0x68, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x69, 0x72, 0x6f, 0x6e, 0x63, 0x6f,
	0x72, 0x65, 0x6c, 0x61, 0x62, 0x73, 0x2e, 0x63, 0x6d, 0x6b, 0x2e, 0x53, 0x61, 0x61, 0x53, 0x53,
	0x68, 0x69, 0x65, 0x6c, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x73,
	0x61, 0x61, 0x73, 0x53, 0x68, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_document_header_proto_rawDescOnce sync.Once
	file_document_header_proto_rawDescData = file_document_header_proto_rawDesc
)

func file_document_header_proto_rawDescGZIP() []byte {
	file_document_header_proto_rawDescOnce.Do(func() {
		file_document_header_proto_rawDescData = protoimpl.X.CompressGZIP(file_document_header_proto_rawDescData)
	})
	return file_document_header_proto_rawDescData
}

var file_document_header_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_document_header_proto_goTypes = []interface{}{
	(*DataControlPlatformHeader)(nil), // 0: proto.ironcorelabs.cmk.DataControlPlatformHeader
	(*SaaSShieldHeader)(nil),          // 1: proto.ironcorelabs.cmk.SaaSShieldHeader
	(*V3DocumentHeader)(nil),          // 2: proto.ironcorelabs.cmk.V3DocumentHeader
}
var file_document_header_proto_depIdxs = []int32{
	0, // 0: proto.ironcorelabs.cmk.V3DocumentHeader.data_control:type_name -> proto.ironcorelabs.cmk.DataControlPlatformHeader
	1, // 1: proto.ironcorelabs.cmk.V3DocumentHeader.saas_shield:type_name -> proto.ironcorelabs.cmk.SaaSShieldHeader
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_document_header_proto_init() }
func file_document_header_proto_init() {
	if File_document_header_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_document_header_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataControlPlatformHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_document_header_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaaSShieldHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_document_header_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*V3DocumentHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_document_header_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*V3DocumentHeader_DataControl)(nil),
		(*V3DocumentHeader_SaasShield)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_document_header_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_document_header_proto_goTypes,
		DependencyIndexes: file_document_header_proto_depIdxs,
		MessageInfos:      file_document_header_proto_msgTypes,
	}.Build()
	File_document_header_proto = out.File
	file_document_header_proto_rawDesc = nil
	file_document_header_proto_goTypes = nil
	file_document_header_proto_depIdxs = nil
}
